### ISSUE TITLE
Deprecate repository?

### ISSUE THREAD

**Issue by jhabdas** [NebulousLabs/entropy-mnemonics#12]
This repository does not appear to be the canonical source code for the following deb package: https://github.com/debian-go/golang-github-nebulouslabs-entropy-mnemonics

The above debian package was updated 9 months ago where as [this GH repository](https://github.com/NebulousLabs/entropy-mnemonics) whereas history shows this GH repo has not been updated in over a year.

Please consider deprecating this repository and/or pointing to the canonical source and noting this copy may not be the latest source code. Thanks.

**Comment by lukechampine** [comment]
This repo is still the canonical source. The Debian repo was created so that Sia could be distributed as a .deb, but it's a third-party project. We (Nebulous) recommend that source code be fetched via `go get`.
